# Generated by Django 5.1.5 on 2025-04-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='two_factory_expiry',
            new_name='two_factor_expiry',
        ),
    ]
