# Generated by Django 5.1.5 on 2025-04-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_two_factory_expiry_customuser_two_factor_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_secret',
        ),
    ]
