# Generated by Django 5.1.5 on 2025-04-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_notes_alter_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
