# Generated by Django 5.1.5 on 2025-04-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_transaction_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Expense',
        ),
    ]
