# Generated by Django 5.1.5 on 2025-04-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
