# Generated by Django 5.1.5 on 2025-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_income_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
